# -*- coding: utf-8 -*-
"""ASSINGNMENT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7LHnhaVK_gMeiXDxJvRjzmMOUId88NF
"""

import random
while(True):
 a=random.randint(10,99)
 b=random.randint(10,99)
 if(a>35 and b>60):
     print("High Temperature and Humidity of:",a,b,"%","Alaram is ON")
 elif(a<35 and b<60):
     print("Normal Temperature and Humidity of:",a,b,"%","Alaram is OFF")
 break